### PR TITLE
send pms to multiple user

### PR DESCRIPTION
**Pull request by blookvoodow**
parameter sendto needs to be an array when invoking the call

### CODE REVIEW

**Comment by githubpsyche** [comment]
Am concerned about what happens if sendto is a string. It will have a length that's nonzero so the function will continue. Then later, it'll loop through each character in the string.

**Comment by githubpsyche** [comment]
Furthermore, I feel like we should try to support a string input if the user wants to specify just one user. Would make clients' code cleaner, I think.

**Comment by blookvoodow** [comment]
also I've noticed that sometimes sendPm will fail silently. I suspect it has something to do with session requests not resolving before we build the form object. I will look into turning them asynchronous and chaining the requests to be more consistent

**Comment by githubpsyche** [comment]
This one seems out of date now that you've made the other pull request.

**Pull request closed without merging**
